version: '3'
services:
  directus:
    image: directus/directus:9.25.1
    ports:
      - "8055:8055"
    volumes:
      - ./path/to/your/directus/files:/var/directus/public
    depends_on:
      - postgres
    environment:
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: dldtuser
      DB_PASSWORD: indkWxPCcn0ZR3wpuGwg
      KEY: "8e7FhBjPm2TnZq4s7v9y$BcEfGhJkMnQ8e7FhBjPm2TnZq4s7v9y$BcEfGhJkMnQ"
      SECRET: "X9F7nD2Rm8PqZuE5hW6JcA4KvL3TgB1yX9F7nD2Rm8PqZuE5hW6JcA4KvL3TgB1y"
      CORS_ORIGIN: "http://localhost:3000"
      CORS_ENABLED: true

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dldtuser
      POSTGRES_PASSWORD: indkWxPCcn0ZR3wpuGwg
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    volumes:
      - ./api/db.sql:/docker-entrypoint-initdb.d/DATABASE_PORT.sql # Mount seed SQL file
